{
 "title": "Main Dashboard",
 "description": "Metrics of the Notes Phoenix app, collected by prom_ex",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Active Port Count",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "notes_prom_ex_beam_stats_port_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "notes_prom_ex_beam_memory_allocated_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Allocated Atoms",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "notes_prom_ex_beam_stats_atom_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Bytes Collected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "notes_prom_ex_beam_stats_gc_reclaimed_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPTIME (MS)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "notes_prom_ex_beam_stats_uptime_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}